# Zola configuration
title = "WordCount Solutions, LLC"
description = "Human-Centered Technical Writing and Editing — On Demand"
base_url = "https://wordcount-solutions.github.io"
theme = "vonge"
taxonomies = [
    { name = "tags", feed = true},
]

[extra]
# Image used for social link previews (Open Graph and Twitter cards).
social_media_share_image = "/images/art/janeb13-computer-1185626%201024x683.jpeg"

# Logo configuration
logo_image = "images/logo3.webp"

# Navigation configuration
# Set to false to hide sections from navigation
show_projects = false
show_blog = false
show_tags = false

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/about", title = "About" },
    { url = "$BASE_URL/contact", title = "Contact" },
    { url = "$BASE_URL/faq", title = "FAQ" },
    { url = "$BASE_URL/services", title = "Services" },
    { url = "$BASE_URL/pricing", title = "Pricing" },
    { url = "$BASE_URL/team-page", title = "Team" },
    { url = "$BASE_URL/philosophy", title = "Philosophy" }
]

# Social media icons in footer
social_icons = [
    { url = "https://github.com/wordcount-solutions", icon = "GitHub" },
    { url = "https://www.linkedin.com/company/wordcount-solutions/posts/?feedView=all", icon = "LinkedIn" }
]

[extra.newsletter]
newsletter_title = "Join our mailing list"
newsletter_description = "Get updates from the team."
newsletter_url = "https://40xak2.share-na2.hsforms.com/2mPzw7WXvReuWIZMS79wh1w"
newsletter_button = "Subscribe"

[extra.footer]
menu = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/about", title = "About" },
    { url = "$BASE_URL/contact", title = "Contact" },
    { url = "$BASE_URL/faq", title = "FAQ" },
    { url = "$BASE_URL/services", title = "Services" },
    { url = "$BASE_URL/team-page", title = "Team" },
    { url = "$BASE_URL/pricing", title = "Pricing" },
    { url = "$BASE_URL/philosophy", title = "Philosophy" },
]

[[extra.content_blocks]]
block = "hero"
title = "Human-Centered Technical Writing and Editing — On Demand"
description_html = "Partner with WordCount Solutions for smart, human-enabled content. We deliver tailored technical writing and editing projects that meet your needs without the hassle of hiring a creative team."
image = "/images/art/janeb13-computer-1185626 1024x683.jpeg"
image_alt = "Woman working at a laptop"
cta_button_link = "mailto:inquiries@wordcount.solutions"
cta_button = "Get in touch"

[[extra.content_blocks]]
block = "team-section"
title = "WordCount Team"
description_html = ""
show_team = true
